### PR TITLE
i3 config: fix typo when moving containers with numpad

### PR DESCRIPTION
**Pull request by itsbekas**
Slight typo in moving containers to workspace 6 with numpad

### CODE REVIEW

**Comment by ulises-jeremias** [comment]
Great! Thank you!!

**Comment by ulises-jeremias** [comment]
Regarding the number of workspaces, no reason at all, I got used to it because I used ArchLabs as inspiration and they used to configure it with 8, but maybe I can try with 10 hehe

**Comment by ulises-jeremias** [comment]
@itsbekas hey! didn't know where else to chat with you 😅 wanted to ask you. Would you like to co-maintain this repository with us? being us mostly me and some other contributors from time to time

if yes, let me know where would you like me to contact you to chat about the details!

**Comment by itsbekas** [comment]
@ulises-jeremias hey! discord is probably the best way to find me if that works for you: `bekas#1273` :sweat_smile: about co-maintaining this, it's hard to find free time these days, but since I use this it'd be fun to help out every now and then

**Pull request merged**
